<div class="header-wrapper col-full" style="padding-top: 51px;">
  <div class="menu-section menu-down">
    <header id="masthead" itemscope="itemscope" itemtype="http://schema.org/WPHeader" class="site-header">
      <div class="df-header-inner df_container-fluid fluid-width fluid-max col-full animated fadeIn">
        <div class="col-left">
          <div id="branding" class="site-branding">
            <a href="http://www.brightpattern.com/" class="df-sitename" rel="home follow" data-wpel-link="internal" target="_self"> <img class="normal-logo" src="http://cdn3.brightpattern.com/wp-content/uploads/2016/07/bright-pattern-logo-mini.png?x94889" alt=""> <img class="sticky-logo" src="http://cdn3.brightpattern.com/wp-content/uploads/2016/07/bright-pattern-logo-mini.png?x94889"
              alt=""> </a>
          </div>
        </div>
        <div class="col-right site-misc-tools">
          <ul>
            <li class="df-ajax-search"><i class="md-search"></i></li>
            <li class="df-menu-off-canvas df-mobile-off-canvas"><i class="md-menu"></i></li>
          </ul>
        </div>
        <div class="menu-align alignright">
          <nav class="main-navigation hidden-tl hidden-sm" id="menu-primary-menu" aria-label="Primary Menu Menu" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
            <ul id="main-nav" class="df-navi">
              <li id="menu-item-37107" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-37107 first has-children"><a href="#" title="Products" data-wpel-link="internal" target="_self" rel="follow"><span>Products</span></a>
                <ul class="sub-nav df_row-fluid">
                  <li id="menu-item-35633" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-35633 first"><a href="http://www.brightpattern.com/cloud-contact-center/" title="Cloud Contact Center" data-wpel-link="internal" target="_self" rel="follow"><span>Cloud Contact Center</span></a></li>
                  <li id="menu-item-36241" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-36241"><a href="http://www.brightpattern.com/call-center-software/multichannel-contact-center/" title="Multichannel Contact Center" data-wpel-link="internal" target="_self" rel="follow"><span>Multichannel Contact Center</span></a></li>
                  <li id="menu-item-7896"
                  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-7896 has-children"><a href="http://www.brightpattern.com/call-center-software/crm-integrations/" title="CRM Integrations" data-wpel-link="internal" target="_self" rel="follow"><span>CRM Integrations</span></a>
                    <ul class="sub-nav df_row-fluid">
                      <li id="menu-item-35190" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-35190 first"><a href="http://www.brightpattern.com/call-center-software/crm-integrations/salesforce-integration/" title="Salesforce" data-wpel-link="internal" target="_self" rel="follow"><span>Salesforce</span></a></li>
                      <li id="menu-item-36202"
                      class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-36202"><a href="http://www.brightpattern.com/call-center-software/crm-integrations/zendesk-integration/" title="Zendesk" data-wpel-link="internal" target="_self" rel="follow"><span>Zendesk</span></a></li>
                      <li id="menu-item-34069" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-34069"><a href="http://www.brightpattern.com/call-center-software/crm-integrations/rightnow-integration-2/" title="RightNow" data-wpel-link="internal" target="_self" rel="follow"><span>RightNow</span></a></li>
                      <li id="menu-item-7924" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7924"><a href="http://www.brightpattern.com/cloud-contact-center-apis/" title="Cloud APIs" data-wpel-link="internal" target="_self" rel="follow"><span>Cloud APIs</span></a></li>
                      <li id="menu-item-37044" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-37044"><a href="http://www.brightpattern.com/call-center-software/crm-integrations/crm-integrations-comparison/" title="CRM Integrations Comparison" data-wpel-link="internal" target="_self" rel="follow"><span>CRM Integrations Comparison</span></a></li>
                    </ul>
                  </li>
                  <li id="menu-item-36317" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-36317"><a href="http://www.brightpattern.com/virtual-contact-center/" title="Virtual Contact Center" data-wpel-link="internal" target="_self" rel="follow"><span>Virtual Contact Center</span></a></li>
                  <li id="menu-item-7679" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7679"><a href="http://www.brightpattern.com/call-center-software/predictive-dialer/" title="Predictive Dialer" data-wpel-link="internal" target="_self" rel="follow"><span>Predictive Dialer</span></a></li>
                  <li id="menu-item-7302" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7302"><a href="http://www.brightpattern.com/call-center-software/enterprise-grade/" title="Enterprise-grade" data-wpel-link="internal" target="_self" rel="follow"><span>Enterprise-grade</span></a></li>
                  <li id="menu-item-7304" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7304"><a href="http://www.brightpattern.com/call-center-software/" title="Comprehensive Capabilities" data-wpel-link="internal" target="_self" rel="follow"><span>Comprehensive Capabilities</span></a></li>
                  <li id="menu-item-37058" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-37058"><a href="http://www.brightpattern.com/call-center-software/integration-accounts/" title="Integration Accounts" data-wpel-link="internal" target="_self" rel="follow"><span>Integrations Directory</span></a></li>
                </ul>
              </li>
              <li id="menu-item-34170" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-34170"><a href="http://www.brightpattern.com/contact-center-pricing/" title="Cloud Contact Center Software Pricing" data-wpel-link="internal" target="_self" rel="follow"><span>Pricing</span></a></li>
              <li id="menu-item-35634" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-35634 has-children"><a href="#" title="Solutions" data-wpel-link="internal" target="_self" rel="follow"><span>Solutions</span></a>
                <ul class="sub-nav df_row-fluid">
                  <li id="menu-item-37093" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-37093 first"><a href="http://www.brightpattern.com/call-center-software/ai-and-bots/" title="AI and Bots Applications" data-wpel-link="internal" target="_self" rel="follow"><span>AI and Bots Applications</span></a></li>
                  <li id="menu-item-7047" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7047"><a href="http://www.brightpattern.com/contact-center-for-bpo/" title="For BPO" data-wpel-link="internal" target="_self" rel="follow"><span>For BPO</span></a></li>
                  <li id="menu-item-7989" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7989"><a href="http://www.brightpattern.com/in-app-customer-support/" title="In-App Mobile Customer Service" data-wpel-link="internal" target="_self" rel="follow"><span>In-App Mobile Customer Service</span></a></li>
                  <li id="menu-item-7674"
                  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7674"><a href="http://www.brightpattern.com/call-center-software/for-visually-impaired/" title="For Visually-Impaired" data-wpel-link="internal" target="_self" rel="follow"><span>For Visually-Impaired</span></a></li>
                  <li id="menu-item-35635"
                  class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-35635"><a href="http://www.brightpattern.com/how-to-reduce-call-abandonment-in-a-call-center/" title="Reduction of Call Abandonment" data-wpel-link="internal" target="_self" rel="follow"><span>Reduction of Call Abandonment</span></a></li>
                </ul>
              </li>
              <li id="menu-item-7049" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-7049 has-children"><a href="http://www.brightpattern.com/white-papers/" title="Resources" data-wpel-link="internal" target="_self" rel="follow"><span>Resources</span></a>
                <ul class="sub-nav df_row-fluid">
                  <li id="menu-item-36220" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-36220 first"><a href="http://blog.brightpattern.com/" title="Blog" data-wpel-link="external" target="_blank" rel="nofollow external noopener noreferrer"><span>Blog</span></a></li>
                  <li id="menu-item-7048" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7048"><a href="http://www.brightpattern.com/white-papers/" title="White Papers" data-wpel-link="internal" target="_self" rel="follow"><span>White Papers</span></a></li>
                  <li id="menu-item-7043" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7043"><a href="http://www.brightpattern.com/contact-center-brochures/" title="Brochures" data-wpel-link="internal" target="_self" rel="follow"><span>Brochures</span></a></li>
                  <li id="menu-item-7045" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7045"><a href="http://www.brightpattern.com/contact-center-resources/" title="Case Studies" data-wpel-link="internal" target="_self" rel="follow"><span>Case Studies</span></a></li>
                  <li id="menu-item-7046" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7046"><a href="http://www.brightpattern.com/contact-center-webinars/" title="On-Demand Webinars" data-wpel-link="internal" target="_self" rel="follow"><span>On-Demand Webinars</span></a></li>
                  <li id="menu-item-7044" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7044"><a href="http://www.brightpattern.com/glossary/" title="Glossary" data-wpel-link="internal" target="_self" rel="follow"><span>Glossary</span></a></li>
                  <li id="menu-item-36415" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-36415"><a href="http://www.brightpattern.com/call-center-calculator/" title="Call Center Calculator" data-wpel-link="internal" target="_self" rel="follow"><span>Call Center Calculator</span></a></li>
                  <li id="menu-item-36198" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-36198"><a href="http://help.brightpattern.com" title="Documentation" data-wpel-link="external" target="_blank" rel="nofollow external noopener noreferrer"><span>Documentation</span></a></li>
                </ul>
              </li>
              <li id="menu-item-7037" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-7037 has-children"><a href="http://www.brightpattern.com/contact-center-support/" title="Contact Center Support" data-wpel-link="internal" target="_self" rel="follow"><span>Support</span></a>
                <ul class="sub-nav df_row-fluid">
                  <li id="menu-item-7321" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7321 first"><a href="http://www.brightpattern.com/contact-center-support/" title="Your Success is Our Goal" data-wpel-link="internal" target="_self" rel="follow"><span>Your Success is Our Goal</span></a></li>
                  <li id="menu-item-36197" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-36197"><a href="http://help.brightpattern.com" title="Documentation" data-wpel-link="external" target="_blank" rel="nofollow external noopener noreferrer"><span>Documentation</span></a></li>
                </ul>
              </li>
              <li id="menu-item-7038" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-7038 has-children"><a href="http://www.brightpattern.com/bright-pattern-company/" title="Company" data-wpel-link="internal" target="_self" rel="follow"><span>Company</span></a>
                <ul class="sub-nav df_row-fluid">
                  <li id="menu-item-7000" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-7000 first"><a href="http://www.brightpattern.com/bright-pattern-company/" title="About Us" data-wpel-link="internal" target="_self" rel="follow"><span>About Us</span></a></li>
                  <li id="menu-item-7039" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7039"><a href="http://www.brightpattern.com/partners/" title="Partners" data-wpel-link="internal" target="_self" rel="follow"><span>Partners</span></a></li>
                  <li id="menu-item-37274" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-37274"><a href="http://www.brightpattern.com/news/" data-wpel-link="internal" target="_self" rel="follow"><span>News</span></a></li>
                  <li id="menu-item-37273" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-37273"><a href="http://www.brightpattern.com/bright-pattern-company/upcoming-events/" data-wpel-link="internal" target="_self" rel="follow"><span>Upcoming Events</span></a></li>
                  <li id="menu-item-7050" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-7050"><a href="http://www.brightpattern.com/media-coverage/" title="Media Coverage" data-wpel-link="internal" target="_self" rel="follow"><span>Media Coverage</span></a></li>
                  <li id="menu-item-36605" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-36605"><a href="http://www.brightpattern.com/bright-pattern-company/review/" title="Bright Pattern Review" data-wpel-link="internal" target="_self" rel="follow"><span>Reviews</span></a></li>
                  <li id="menu-item-7001" class=" menu-item menu-item-type-custom menu-item-object-custom menu-item-7001"><a href="http://www.brightpattern.com/careers/" title="Careers" data-wpel-link="internal" target="_self" rel="follow"><span>Careers</span></a></li>
                  <li id="menu-item-34260" class=" menu-item menu-item-type-post_type menu-item-object-page menu-item-34260"><a href="http://www.brightpattern.com/contacts/" title="Contacts" data-wpel-link="internal" target="_self" rel="follow"><span>Contacts</span></a></li>
                </ul>
              </li>
              <li id="menu-item-36337" class="button popmake-33947 menu-item menu-item-type-custom menu-item-object-custom menu-item-36337  pum-trigger" data-popup="33947" style="cursor: pointer;"><a href="#" data-wpel-link="internal" target="_self" rel="follow"><span>Request Demo</span></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  </div>
</div>

